import { v4 as uuid } from "uuid";
import faker from "@faker-js/faker";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

// ADD STOCK QUANTITY TO EACH PRODUCTS

export const products = [
  // Rackets
  {
    _id: uuid(),
    title: "Nanoray Light 18i",
    categoryName: "racquets",
    brand: "yonex",
    image: "https://rukminim2.flixcart.com/image/612/612/kctf0cw0/racquet/x/6/f/g4-8-25-cm-nanoray-light-18i-pack-of-1-strung-1-nnaoray-18i-80-original-imaftuvf3eygetnh.jpeg?q=70",
    tags: "trending",
    price: 1899,
    ratings: {stars:4.3,count:1235},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: false,
    discount:10,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },  
  {
    _id: uuid(),
    title: "Smash XP 707 Pro",
    categoryName: "racquets",
    brand: "li ning",
    image: "https://rukminim2.flixcart.com/image/612/612/kiow6fk0-0/racquet/f/f/p/g4-3-25-inches-strung-smash-xp-303-pro-1-smash-xp-303-pro-90-original-imafyfcnchke2ny9.jpeg?q=70  ",
    tags: "",
    price: 1599,
    ratings: {stars:3.9,count:1235},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: false,
    discount:15,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "Hypernano X 900X (Dominator)",
    categoryName: "racquets",
    brand: "cartlon",
    image: "https://rukminim2.flixcart.com/image/612/612/jvzkb680/racquet/z/5/h/g5-3-inches-hypernano-x-900x-dominator-all-round-series-4u-original-imafgqhtpjpf6vbk.jpeg?q=70",
    tags: "trending",
    price: 12675,
    ratings: {stars:4.1,count:235},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: false,
    discount:15,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "ZR 100 LIGHT",
    categoryName: "racquets",
    brand: "yonex",
    image: "https://rukminim2.flixcart.com/image/612/612/kctf0cw0/racquet/u/v/k/g4-8-25-cm-zr-100-light-strung-1-na-400-badminton-racquet-yonex-original-imaftuvfyays8vkg.jpeg?q=70",
    tags: "trending",
    price: 1200,
    ratings: {stars:3.8,count:1935},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: true,
    discount:10,
    idealFor: faker.random.arrayElement([
      "All",
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "Windstorm 72",
    categoryName: "racquets",
    brand: "li ning",
    image: "https://rukminim2.flixcart.com/image/612/612/k4vmxzk0/racquet/d/b/h/g4-3-25-inches-windstorm-72-unstrung-1-aypn108-4-72-badminton-original-imafnzvhkgpwebag.jpeg?q=70",
    tags: "new",
    price: 9399,
    ratings: {stars:3.9,count:295},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: false,
    discount:10,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },

  // shoes
  {
    _id: uuid(),
    title: "860 Running Shoes",
    categoryName: "shoes",
    brand: "new balance",
    image: "https://rukminim2.flixcart.com/image/570/684/kzd147k0/shoe/j/y/u/11-5-m860l10-12-new-balance-blue-original-imagbdvyenerzkbt.jpeg?q=50",
    tags: "new",
    price: 7200,
    ratings: {stars:4.9,count:95},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: false,
    discount:20,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "ULTRABOOST 22",
    categoryName: "shoes",
    brand: "adidas",
    image: "https://rukminim2.flixcart.com/image/570/684/kzd147k0/shoe/c/8/a/6-gx3061-6-adidas-legind-blurus-turbo-original-imagbe69ehzp2c23.jpeg?q=50",
    tags: "trending",
    price: 17999,
    ratings: {stars:4.2,count:95},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: false,
    discount:10,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "90s TENNIS",  
    categoryName: "shoes",
    brand: "adidas",
    image: "https://rukminim2.flixcart.com/image/570/684/l0cr4i80/shoe/l/l/y/-original-imagc572hyg5vyqq.jpeg?q=50",
    tags: "",
    price: 4799,
    ratings: {stars:2.9,count:1295},
    stockQty: 40,
    comingSoon: true,
    inStock: true,
    fastDelivery: false,
    discount:10,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "Badminton Shoes",
    categoryName: "shoes",
    brand: "nivia",
    image: "https://rukminim2.flixcart.com/image/570/684/krjjde80/shoe/a/p/i/8-vb-694bb-8-nivia-blue-black-original-imag5axxhkac23gx.jpeg?q=50",
    tags: "new",
    price: 1869,
    ratings: {stars:4.5,count:22295},
    stockQty: 0,
    comingSoon: false,
    inStock: false,
    fastDelivery: true,
    discount:25,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "Ferrari X-Ray Speed",
    categoryName: "shoes",
    brand: "puma",
    image: "https://rukminim2.flixcart.com/image/570/684/kzegk280/shoe/o/8/i/9-307033-9-puma-white-smoked-pearl-black-original-imagbf4b34wj8jww.jpeg?q=50",
    tags: "trending",
    price: 4399,
    ratings: {stars:4.2,count:2295},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: true,
    discount:25,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },

  // apparel
  {
    _id: uuid(),
    title: "Round Neck",
    categoryName: "apparel",
    brand: "adidas",
    image: "https://rukminim2.flixcart.com/image/570/684/ku8pbbk0/t-shirt/v/v/n/m-gs6306-adidas-original-imag7eh5u5jvsbew.jpeg?q=50",
    tags: "new",
    price: 1399,
    ratings: {stars:4.2,count:95},
    stockQty: 35,
    comingSoon: false,
    inStock: true,
    fastDelivery: true,
    discount:20,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "Block Men V",
    categoryName: "apparel",
    brand: "puma",
    image: "https://rukminim2.flixcart.com/image/570/684/kmxsakw0/t-shirt/k/r/j/s-76839201-puma-original-imagfqdgjmfdqwfk.jpeg?q=50",
    tags: "trending",
    price: 1199,
    ratings: {stars:4.4,count:595},
    stockQty: 45,
    comingSoon: false,
    inStock: true,
    fastDelivery: true,
    discount:35,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "Round Neck Brown",
    categoryName: "apparel",
    brand: "new balance",
    image: "https://rukminim2.flixcart.com/image/570/684/ky4qgsw0/t-shirt/g/p/f/-original-imagafgchmhzshvm.jpeg?q=50",
    tags: "trending",
    price: 1959,
    ratings: {stars:3.9,count:225},
    stockQty: 30,
    comingSoon: true,
    inStock: true,
    fastDelivery: true,
    discount:45,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "Puma Motorsport",
    categoryName: "apparel",
    brand: "puma",
    image: "https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/13557224/2021/2/22/42f393e0-9a67-4323-96fa-e746a119f3a61613979453725-Puma-Men-Tshirts-4581613979452074-1.jpg",
    tags: "new",
    price: 1399,
    ratings: {stars:4.7,count:252},
    stockQty: 40,
    comingSoon: false,
    inStock: false,
    fastDelivery: true,
    discount:25,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "ad Speed",
    categoryName: "apparel",
    brand: "adidas",
    image: "https://rukminim2.flixcart.com/image/570/684/ks3jjbk0/t-shirt/q/p/u/s-gl0769-adidas-original-imag5qp3bfhbgnqd.jpeg?q=50",
    tags: "new",
    price: 2399,
    ratings: {stars:3.9,count:2395},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: true,
    discount:50,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },

  // bags
  {
    _id: uuid(),
    title: "YONEX MSQ13MS3",
    categoryName: "bags",
    brand: "yonex",
    image: "https://rukminim2.flixcart.com/image/612/612/k73nlow0/sport-bag/h/v/h/m-tournament-bag-msq13ms3-bt6-lcw-edition-msq13ms3-bt6-lcw-original-imafpebv2yhjb2yy.jpeg?q=70",
    tags: "trending",
    price: 1919,
    ratings: {stars:4.5,count:239},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: true,
    discount:10,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: " Bag SUNR BRB1",
    categoryName: "bags",
    brand: "yonex",
    image: "https://rukminim2.flixcart.com/image/612/612/kt1u3rk0/sport-bag/o/t/s/l-badminton-bag-sunr-brb11ms2-bt6-s-with-shoe-pocket-brb11ms2-original-imag6gmuqrkmqbpv.jpeg?q=70",
    tags: null,
    price: 3599,
    ratings: {stars:4.3,count:5641},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: true,
    discount:32,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "LI-NING ABDN146",
    categoryName: "bags",
    brand: "li ning",
    image: "https://rukminim2.flixcart.com/image/612/612/jlph9jk0/sport-bag/g/2/g/na-l-abdn146-3-li-ning-na-original-imaf8rueehpckzfr.jpeg?q=70",
    tags: "new",
    price: 1789,
    ratings: {stars:4.1,count:2239},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: true,
    discount:60,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "Nivia Kobo",
    categoryName: "bags",
    brand: "nivia",
    image: "https://rukminim2.flixcart.com/image/612/612/k7qinbk0/free-weight/f/z/a/sandbag-ko-1-25-kobo-original-imafpwemusjwp9nj.jpeg?q=70",
    tags: "trending",
    price: 5119,
    ratings: {stars:4.2,count:2239},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: true,
    discount:35,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },
  {
    _id: uuid(),
    title: "NIVIA PACE 2",
    categoryName: "bags",
    brand: "nivia",
    image: "https://rukminim2.flixcart.com/image/612/612/kokdci80/sport-bag/z/e/f/m-sports-pace-2-5179-nivia-22-l-original-imag2ztjmmcwcxvg.jpeg?q=70",
    tags: null,
    price: 919,
    ratings: {stars:4.2,count:2339},
    stockQty: 40,
    comingSoon: false,
    inStock: true,
    fastDelivery: true,
    discount:35,
    idealFor: faker.random.arrayElement([
      "Men",
      "Women",
      "Girl",
      "Boy",
      "Senior",
    ]),
    level: faker.random.arrayElement([
      "all levels",
      "beginner",
      "amateur",
      "intermediate",
      "advanced",
      "professional",
    ]),
    services: faker.random.arrayElement([
    "7 Days Replacement Policy",
    "14 Days Return Policy",
    "1 Year Limited Domestic Brand Warranty",
    "Cash on Delivery available",
  ]),
  },

];
